#!/usr/bin/env sh

# bar settings

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          autofocus
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config window_shadow                on
yabai -m config window_border                on
yabai -m config window_border_placement      exterior
yabai -m config window_border_width          2
yabai -m config window_border_radius         -1.0
yabai -m config active_window_border_topmost on
yabai -m config active_window_border_color   0xffFF8500
yabai -m config normal_window_border_color   0x00505050 # alpha is 0
yabai -m config insert_window_border_color   0xffd75f5f # insert means selected but focused
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  36
yabai -m config bottom_padding               10
yabai -m config left_padding                 10
yabai -m config right_padding                10
yabai -m config window_gap                   10

# float system preferences
yabai -m rule --add app='^System Preferences$' manage=off

# update battery loop from wiki
# https://github.com/koekeishiya/yabai/wiki/Tips-and-tricks#updating-battery-icon-in-status-bar-based-on-battery-level
function update_battery_loop() {
	while true; do
		# Get the current battery percentage.
		battery=$(pmset -g batt | grep -Eo "\d+%" | cut -d% -f1)

		if [ $battery -gt 84 ]; then
			yabai -m config status_bar_power_icon_strip battery-full plug
		elif [ $battery -gt 60 ]; then
			yabai -m config status_bar_power_icon_strip battery-three-quarters plug
		elif [ $battery -gt 39 ]; then
			yabai -m config status_bar_power_icon_strip battery-half plug
		elif [ $battery -gt 14 ]; then
			yabai -m config status_bar_power_icon_strip battery-quarter plug
		else
			yabai -m config status_bar_power_icon_strip battery-empty plug
		fi

		# wait 5 seconds
		sleep 5
	done
}
# run the function async
update_battery_loop &

echo "yabai configuration loaded.."

