[general]
import = ["~/.config/alacritty/aura-theme.toml"]

[font]
size = 20

[font.normal]
family = "MesloLGL Nerd Font"

[scrolling]
history = 12000

[window]
opacity = 0.9

[[keyboard.bindings]]
key = "Minus"
mods = "Control"
action = "DecreaseFontSize"

[[keyboard.bindings]]
key = "Equals"
mods = "Control"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "0"
mods = "Control"
action = "ResetFontSize"
